jwt:
  header: Authorization
  secret: swjtuhcxxgcx
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      login: "auth/login"
      refresh: "auth/refresh"
      register: "auth/register"